lucab/caps-rs

- Cargo.toml
- src/ambient.rs
- src/base.rs
- src/bounding.rs
- src/errors.rs
- src/lib.rs
This contains some major API cleanups towards 0.1:
* introduce an `errors` module
* remove custom derive via macros
> lib: interface cleanup

- examples/legacy.rs
- src/lib.rs
- src/runtime.rs
- tests/runtime.rs
This introduces a module with some methods to detect kernel features
at runtime.
Fixes https://github.com/lucab/caps-rs/issues/7
> runtime: add kernel features auto-detection

- src/nr.rs
For x86 (32bit) the required type for the libc::syscall is i32 over i64.
This changes the type of the constants in nr.rs so the crate compiles on
that architecture.
Fixes #17
> Change type for x86 constants in nr

- Cargo.toml
Note: this is a breaking change as it affects public traits.
> cargo: update error-chain to 0.12

- src/lib.rs
- src/nr.rs
- src/securebits.rs
- tests/securebits.rs
This adds initial support for securebits, starting from
`GET_KEEPCAPS` and `SET_KEEPCAPS`.
Closes: https://github.com/lucab/caps-rs/issues/26
> securebits: add support for keepcaps flag

- src/nr.rs
CAPGET and CAPSET weren't defined on those architectures.  I used the
syscall numbers reported at https://golang.org/src/syscall/, and tested
them using qemu user-mode emulation.
I also defined the constants for s390x, but didn't test them.
Also, I fixed the size of powerpc's CAPGET and CAPSET constants.
Fixes #33
> Fix the build on powerpc64 and mips64

- COPYRIGHT
- LICENSE-APACHE-2.0
- LICENSE-MIT
This adds licensing and copyright details.
Closes: https://github.com/lucab/caps-rs/issues/36
> docs: add licenses and copyright

- src/nr.rs
caps-rs currently fails to build on Debian sparc64 with:
```
error[E0425]: cannot find value `CAPGET` in module `nr`
--> src/base.rs:12:40
|
12 |     let r = unsafe { libc::syscall(nr::CAPGET, hdr, data) };
|                                        ^^^^^^ not found in `nr`
error[E0425]: cannot find value `CAPSET` in module `nr`
--> src/base.rs:20:40
|
20 |     let r = unsafe { libc::syscall(nr::CAPSET, hdr, data) };
|                                        ^^^^^^ not found in `nr`
error: aborting due to 2 previous errors
```
With this PR, caps-rs builds fine on Debian sparc64.
> nr: fix build on sparc and sparc64

- Cargo.toml
- src/lib.rs
- src/runtime.rs
This marks the `Capability` enum as non-exhaustive, as the Linux kernel is adding more capabilities.
> caps: mark enum as non-exhaustive

- .travis.yml
This adds the following new platforms for testing on Travis:
ppc64le, arm64, and s390x.
> ci: test on multiple architectures

- Cargo.toml
- src/ambient.rs
- src/base.rs
- src/bounding.rs
- src/errors.rs
- src/lib.rs
- src/runtime.rs
- src/securebits.rs
This switches error handling logic from the `error_chain` library
to `thiserror`.
> errors: switch to thiserror

- .travis.yml
- README.md
- examples/clear_permitted.rs
- examples/legacy.rs
- examples/manipulate_sys_nice.rs
- examples/parse.rs
- src/base.rs
- src/lib.rs
- tests/ambient.rs
- tests/bounding.rs
- tests/effective.rs
- tests/runtime.rs
- tests/securebits.rs
This changes `caps::set()` signature to borrow its `CapsHashSet` argument instead of taking ownership of it.
> lib: switch 'set' to borrow its argument

- Cargo.toml
Changes:
* lib: switch 'set' to borrow its argument
* errors: switch to thiserror
* ci: test on multiple architectures
* cargo: switch to edition 2018
* runtime: support procfs cap_last_cap
* caps: mark enum as non-exhaustive
* ci: bump toolchains
* caps: fix warnings
> cargo: caps release 0.4.0-alpha.1

- src/ambient.rs
- src/bounding.rs
- tests/runtime.rs
When running on older systems, the set of capabilities supported by
this library could be bigger than those effectively known by
the kernel.
This removes some library assumptions about kernel-supported
capabilities. Thus it allows manipulating the ambient and bounding
set in a graceful way, relying on runtime introspection.
> caps: gracefully support older kernel versions

- src/lib.rs
- src/nr.rs
Two new capabilities (`CAP_PERFMON` and `CAP_BPF`) have been introduced in Linux 5.8:
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/capability.h?id=980737282232b752bb14dab96d77665c15889c36
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/include/uapi/linux/capability.h?id=a17b53c4a4b55ec322c132b6670743612229ee9c
Closes: https://github.com/lucab/caps-rs/issues/54
> nr: add CAP_PERFMON and CAP_BPF

- Cargo.toml
Changes:
* caps: gracefully support older kernel versions
* nr: add CAP_PERFMON and CAP_BPF
> cargo: caps release 0.4.0-alpha.2

- Cargo.toml
- src/lib.rs
- src/nr.rs
This adds the new capability `CAP_CHECKPOINT_RESTORE` (number `40`) which has been
introduced in Linux 5.9.
Ref: https://github.com/torvalds/linux/commit/124ea650d3072b005457faed69909221c2905a1f
Closes: #61
> nr: add CAP_CHECKPOINT_RESTORE

- examples/all_caps.rs
This adds an example showing how to introspect all known capabilties,
explaining the difference between the static library set and the
dynamic kernel runtime set.
> examples: show how to introspect all capabilities

- src/nr.rs
The x32 ABI uses the 0x40000000 bit in syscall numbers. Additionally, the x32 ABI keeps syscall numbers as type long, but its type long is i32 rather than i64.
> Fix syscall definitions for x86_64-unknown-linux-gnux32.

- src/bounding.rs
A trivial flaw that mssively confused me today:
The returned on a `PR_CAPBSET_DROP` error is fixed to the acutally used prctl value that failed.
> lib: fix bounding drop error message

- .github/workflows/rust.yml
- src/lib.rs
This bumps clippy to 1.53.0 and adapts the code for new warnings.
> ci: bump linting toolchain to latest stable

- Cargo.toml
- src/ambient.rs
- src/base.rs
- src/bounding.rs
- src/securebits.rs
Unsure if there was a reason for the decision to use the errno crate, but if you just need error printing `std::io::Error::last_os_error()` will do basically the same thing afaik.
> Remove dependency on `errno` crate in favor of std functions

- src/nr.rs
The LoongArch architecture (LoongArch) is an Instruction Set Architecture (ISA) that has a RISC style.
Documentations:
ISA:
https://loongson.github.io/LoongArch-Documentation/LoongArch-Vol1-EN.html
ABI:
https://loongson.github.io/LoongArch-Documentation/LoongArch-ELF-ABI-EN.html
More docs can be found at:
https://loongson.github.io/LoongArch-Documentation/README-EN.html
> Add CAPGET and CAPSET for LoongArch64

- .github/workflows/rust.yml
This updates the minimum Rust toolchain used in CI, in order to match requirements from all dependencies.
> ci: update minimum and linting toolchain to 1.61
